services:
  # Backend Services
  auth:
    build:
      context: ./auth
    ports:
      - "4000:3000"
    environment:
      - MONGO_URI=mongodb://admin:password@auth-db:27017/auth-db?authSource=admin
    depends_on:
      - auth-db
    networks:
      - backend

  cart:
    build:
      context: ./cart
    ports:
      - "6000:3000"
    environment:
      - MONGO_URI=mongodb://admin:password@cart-db:27017/cart-db?authSource=admin
    depends_on:
      - cart-db
    networks:
      - backend

  product:
    build:
      context: ./product
    ports:
      - "7000:3000"
    environment:
      - MONGO_URI=mongodb://admin:password@product-db:27017/product-db?authSource=admin
    depends_on:
      - product-db
    networks:
      - backend
  order:
    build:
      context: ./order
    ports:
      - "8000:3000"
    environment:
      - MONGO_URI=mongodb://admin:password@order-db:27017/order-db?authSource=admin
    depends_on:
      - order-db
    networks:
      - backend

  # Frontend
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"
    networks:
      - backend

  # API Gateway
  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - auth
      - product
      - cart
      - order

  # Databases
  mongo-express-auth-db:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@auth-db:27017
    depends_on:
      - auth-db
    networks:
      - backend

  auth-db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data-auth:/data/db
    networks:
      - backend

  mongo-express-product-db:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@product-db:27017
    depends_on:
      - product-db
    networks:
      - backend

  product-db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data-product:/data/db
    networks:
      - backend

  mongo-express-order-db:
    image: mongo-express
    restart: always
    ports:
      - "8084:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@order-db:27017
    depends_on:
      - order-db
    networks:
      - backend

  order-db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data-order:/data/db
    networks:
      - backend

  mongo-express-cart-db:
    image: mongo-express
    restart: always
    ports:
      - "8083:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@cart-db:27017
    depends_on:
      - cart-db
    networks:
      - backend

  cart-db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - backend

networks:
  backend:


volumes:
  mongo-data-auth:
  mongo-data-product:
  mongo-data-order:
